// src/utils/email.js
'use strict';

const nodemailer = require('nodemailer');
const config = require('../config');
const logger = require('./logger');

let transporter = null;

function getTransporter() {
  if (!transporter) {
    transporter = nodemailer.createTransport({
      host: config.email.host,
      port: config.email.port,
      secure: config.email.port === 465,
      auth: {
        user: config.email.user,
        pass: config.email.pass,
      },
    });
  }
  return transporter;
}

async function sendOTP(email, otp, name = '') {
  if (!config.email.user) {
    logger.warn('Email not configured - OTP would be:', otp);
    // In dev mode, log OTP to console
    if (config.app.isDev) {
      logger.info(`DEV OTP for ${email}: ${otp}`);
    }
    return;
  }

  try {
    await getTransporter().sendMail({
      from: config.email.from,
      to: email,
      subject: 'Your Fitness App OTP',
      html: `
        <div style="font-family:sans-serif;max-width:480px;margin:0 auto;padding:32px;background:#f9fafb;border-radius:12px;">
          <h2 style="color:#1a1a2e;margin-bottom:8px;">🏋️ Fitness App</h2>
          <p style="color:#555;">Hi ${name || 'there'},</p>
          <p style="color:#555;">Your OTP to reset your PIN:</p>
          <div style="background:#fff;border:2px solid #667eea;border-radius:8px;padding:24px;text-align:center;margin:24px 0;">
            <span style="font-size:36px;font-weight:700;letter-spacing:8px;color:#667eea;">${otp}</span>
          </div>
          <p style="color:#888;font-size:13px;">Valid for ${config.otp.expiresMin} minutes. Do not share this OTP with anyone.</p>
          <p style="color:#888;font-size:12px;">If you didn't request this, ignore this email.</p>
        </div>
      `,
    });
    logger.info(`OTP sent to ${email}`);
  } catch (err) {
    logger.error({ err }, 'Failed to send OTP email');
    throw new Error('Failed to send email');
  }
}

async function sendWeeklyDigest(email, name, insightText) {
  if (!config.email.user) return;
  try {
    await getTransporter().sendMail({
      from: config.email.from,
      to: email,
      subject: `${name}'s Weekly Fitness Story 🏆`,
      html: `
        <div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:32px;background:#f9fafb;border-radius:12px;">
          <h2 style="color:#1a1a2e;">🏋️ Your Weekly Fitness Story</h2>
          <div style="background:#fff;border-radius:8px;padding:24px;line-height:1.8;color:#333;">
            ${insightText.replace(/\n/g, '<br>')}
          </div>
          <p style="color:#888;font-size:12px;margin-top:24px;">Generated by AI based on your actual fitness data.</p>
        </div>
      `,
    });
  } catch (err) {
    logger.error({ err }, 'Failed to send weekly digest');
  }
}

module.exports = { sendOTP, sendWeeklyDigest };
